
version: 2
updates:
  # Keep npm dependencies up-to-date
  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json file
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
