
version: 1
updates:
  # Keep npm dependencies up-to-date
  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json file
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
